import * as THREE from 'three';
import {random} from './course';
import type {RallyVehicle} from './vehicle';
// floor: ground height where the particle was thrown. Clumps land within a
// metre or two, so they settle on it instead of looking the road up each step.
type Particle={life:number;max:number;x:number;y:number;z:number;vx:number;vy:number;vz:number;size:number;floor:number};
export class TireEffects{
 clumps:THREE.InstancedMesh;dust:THREE.Points;tracks:THREE.Mesh;particles:Particle[];puffs:Particle[];nextClump=0;nextPuff=0;nextTrack=0;maxClumps=480;maxDust=320;maxTracks=20000;dummy=new THREE.Object3D();rand=random(294);emitCarry=[0,0,0,0];lastContacts:(THREE.Vector3|null)[]=[null,null,null,null];dustPositions:Float32Array;dustSizes:Float32Array;dustAlphas:Float32Array;trackPositions:Float32Array;trackColors:Float32Array;
 constructor(scene:THREE.Scene){this.clumps=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(.065,0),new THREE.MeshStandardMaterial({color:'#735133',roughness:1}),this.maxClumps);this.clumps.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.clumps.frustumCulled=false;scene.add(this.clumps);const particle=():Particle=>({life:0,max:1,x:0,y:-100,z:0,vx:0,vy:0,vz:0,size:0,floor:-100});this.particles=Array.from({length:this.maxClumps},particle);this.puffs=Array.from({length:this.maxDust},particle);this.dustPositions=new Float32Array(this.maxDust*3);this.dustSizes=new Float32Array(this.maxDust);this.dustAlphas=new Float32Array(this.maxDust);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(this.dustPositions,3).setUsage(THREE.DynamicDrawUsage));g.setAttribute('pSize',new THREE.BufferAttribute(this.dustSizes,1).setUsage(THREE.DynamicDrawUsage));g.setAttribute('pAlpha',new THREE.BufferAttribute(this.dustAlphas,1).setUsage(THREE.DynamicDrawUsage));this.dust=new THREE.Points(g,new THREE.ShaderMaterial({uniforms:{height:{value:800},pixelRatio:{value:1}},vertexShader:'attribute float pSize;attribute float pAlpha;varying float vAlpha;uniform float height;uniform float pixelRatio;void main(){vec4 p=modelViewMatrix*vec4(position,1.0);vAlpha=pAlpha;gl_Position=projectionMatrix*p;gl_PointSize=clamp(pSize*height*pixelRatio/(-p.z),0.,110.);}',fragmentShader:'varying float vAlpha;void main(){float r=length(gl_PointCoord-vec2(.5))*2.;float a=(1.-smoothstep(.1,1.,r))*vAlpha;if(a<.004)discard;gl_FragColor=vec4(.66,.52,.34,a);}',transparent:true,depthWrite:false}));this.dust.frustumCulled=false;scene.add(this.dust);
 this.trackPositions=new Float32Array(this.maxTracks*12);this.trackColors=new Float32Array(this.maxTracks*12);const indices=new Uint32Array(this.maxTracks*6);for(let i=0;i<this.maxTracks;i++)indices.set([i*4,i*4+1,i*4+2,i*4+2,i*4+1,i*4+3],i*6);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(this.trackPositions,3).setUsage(THREE.DynamicDrawUsage));geo.setAttribute('color',new THREE.BufferAttribute(this.trackColors,3).setUsage(THREE.DynamicDrawUsage));geo.setIndex(new THREE.BufferAttribute(indices,1));geo.setDrawRange(0,0);this.tracks=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:.4,depthWrite:false,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2}));this.tracks.frustumCulled=false;this.tracks.renderOrder=2;scene.add(this.tracks);const zero=new THREE.Matrix4().makeScale(0,0,0);for(let i=0;i<this.maxClumps;i++)this.clumps.setMatrixAt(i,zero);
 }
 step(dt:number,v:RallyVehicle,enabled:boolean){const rand=this.rand;if(enabled&&v.speed>.8){for(let i=0;i<4;i++){const w=v.wheels[i];if(!w.contact){this.lastContacts[i]=null;continue;}this.emitCarry[i]+=dt*(8+v.speed*1.8+v.throttle*v.speed*2.1+w.slip*v.speed*2.5)*(w.mud?1.25:1);while(this.emitCarry[i]>=1){this.emitCarry[i]--;const p=this.particles[this.nextClump++%this.maxClumps],kick=1.1+v.throttle*4+w.slip*3;Object.assign(p,{x:w.contactPoint.x+(rand()-.5)*.3,y:w.contactPoint.y+.1,z:w.contactPoint.z+(rand()-.5)*.3,vx:v.velocity.x*.18-v.forward.x*kick+(rand()-.5)*3,vy:1.3+rand()*3.5+v.throttle*1.8,vz:v.velocity.z*.18-v.forward.z*kick+(rand()-.5)*3,life:.6+rand()*.7,max:1.2,size:.3+rand()*(w.mud?1.8:1.2),floor:w.contactPoint.y});if(!w.mud&&rand()<.35){const puff=this.puffs[this.nextPuff++%this.maxDust];Object.assign(puff,{x:p.x,y:p.y+.3,z:p.z,vx:p.vx*.6+.4,vy:.4+rand()*.6,vz:p.vz*.6,life:1.6+rand(),max:2.6,size:.2+rand()*.25});}}this.track(i,new THREE.Vector3(w.contactPoint.x,w.contactPoint.y+.029,w.contactPoint.z),w.mud,w.slip);}}else this.lastContacts=[null,null,null,null];
 for(let i=0;i<this.maxClumps;i++){const p=this.particles[i];if(p.life>0){p.life-=dt;p.vy-=9.81*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;if(p.life>.15&&p.y<p.floor){p.y=p.floor+.025;p.vy=Math.abs(p.vy)*.15;p.vx*=.65;p.vz*=.65;p.life=Math.min(p.life,.18);}this.dummy.position.set(p.x,p.y,p.z);this.dummy.rotation.x+=dt*6;this.dummy.rotation.z+=dt*3;this.dummy.scale.setScalar(p.life>0?p.size*Math.min(1,p.life/.15):0);}else if(p.size>0){p.size=0;this.dummy.scale.setScalar(0);}else continue;this.dummy.updateMatrix();this.clumps.setMatrixAt(i,this.dummy.matrix);}this.clumps.instanceMatrix.needsUpdate=true;
 for(let i=0;i<this.maxDust;i++){const p=this.puffs[i];if(p.life>0){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-dt*.7);p.vz*=Math.exp(-dt*.7);this.dustPositions.set([p.x,p.y,p.z],i*3);this.dustSizes[i]=p.size+(1-p.life/p.max)*.7;this.dustAlphas[i]=Math.min(.18,p.life*.14);}else this.dustAlphas[i]=0;}for(const key of ['position','pSize','pAlpha'])this.dust.geometry.attributes[key].needsUpdate=true;
 }
 private track(i:number,p:THREE.Vector3,mud:boolean,slip:number){const last=this.lastContacts[i];if(!last){this.lastContacts[i]=p;return;}const len=last.distanceTo(p);if(len<.27)return;if(len>3){this.lastContacts[i]=p;return;}const dx=(p.x-last.x)/len,dz=(p.z-last.z)/len,w=.15+slip*.05,k=(this.nextTrack++%this.maxTracks)*12;this.trackPositions.set([last.x-dz*w,last.y,last.z+dx*w,last.x+dz*w,last.y,last.z-dx*w,p.x-dz*w,p.y,p.z+dx*w,p.x+dz*w,p.y,p.z-dx*w],k);const c=mud?[.13,.095,.047]:[.26,.17,.085];for(let j=0;j<4;j++)this.trackColors.set(c,k+j*3);for(const key of ['position','color']){const a=this.tracks.geometry.attributes[key] as THREE.BufferAttribute;a.addUpdateRange(k,12);a.needsUpdate=true;}this.tracks.geometry.setDrawRange(0,Math.min(this.nextTrack,this.maxTracks)*6);this.lastContacts[i]=p;}
 resize(h:number,dpr:number){const m=this.dust.material as THREE.ShaderMaterial;m.uniforms.height.value=h;m.uniforms.pixelRatio.value=dpr;}
 clear(){this.particles.forEach(p=>p.life=0);this.puffs.forEach(p=>p.life=0);this.emitCarry=[0,0,0,0];this.nextTrack=0;this.lastContacts=[null,null,null,null];this.tracks.geometry.setDrawRange(0,0);}
 dispose(){for(const o of [this.clumps,this.dust,this.tracks]){o.geometry.dispose();(o.material as THREE.Material).dispose();o.removeFromParent();}}
}
export {RallyAudio} from './audio';
