import * as THREE from 'three';
import {random,nearestRoad,roadHeight,terrainHeight} from './course';
import type {RallyVehicle} from './vehicle';
type Particle={life:number;max:number;x:number;y:number;z:number;vx:number;vy:number;vz:number;size:number};
export class TireEffects{
 clumps:THREE.InstancedMesh;dust:THREE.Points;tracks:THREE.Mesh;particles:Particle[];puffs:Particle[];nextClump=0;nextPuff=0;nextTrack=0;maxClumps=480;maxDust=320;maxTracks=20000;dummy=new THREE.Object3D();rand=random(294);emitCarry=[0,0,0,0];lastContacts:(THREE.Vector3|null)[]=[null,null,null,null];dustPositions:Float32Array;dustSizes:Float32Array;dustAlphas:Float32Array;trackPositions:Float32Array;trackColors:Float32Array;
 constructor(scene:THREE.Scene){this.clumps=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(.065,0),new THREE.MeshStandardMaterial({color:'#735133',roughness:1}),this.maxClumps);this.clumps.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.clumps.frustumCulled=false;scene.add(this.clumps);const particle=():Particle=>({life:0,max:1,x:0,y:-100,z:0,vx:0,vy:0,vz:0,size:0});this.particles=Array.from({length:this.maxClumps},particle);this.puffs=Array.from({length:this.maxDust},particle);this.dustPositions=new Float32Array(this.maxDust*3);this.dustSizes=new Float32Array(this.maxDust);this.dustAlphas=new Float32Array(this.maxDust);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(this.dustPositions,3).setUsage(THREE.DynamicDrawUsage));g.setAttribute('pSize',new THREE.BufferAttribute(this.dustSizes,1).setUsage(THREE.DynamicDrawUsage));g.setAttribute('pAlpha',new THREE.BufferAttribute(this.dustAlphas,1).setUsage(THREE.DynamicDrawUsage));this.dust=new THREE.Points(g,new THREE.ShaderMaterial({uniforms:{height:{value:800},pixelRatio:{value:1}},vertexShader:'attribute float pSize;attribute float pAlpha;varying float vAlpha;uniform float height;uniform float pixelRatio;void main(){vec4 p=modelViewMatrix*vec4(position,1.0);vAlpha=pAlpha;gl_Position=projectionMatrix*p;gl_PointSize=clamp(pSize*height*pixelRatio/(-p.z),0.,110.);}',fragmentShader:'varying float vAlpha;void main(){float r=length(gl_PointCoord-vec2(.5))*2.;float a=(1.-smoothstep(.1,1.,r))*vAlpha;if(a<.004)discard;gl_FragColor=vec4(.66,.52,.34,a);}',transparent:true,depthWrite:false}));this.dust.frustumCulled=false;scene.add(this.dust);
 this.trackPositions=new Float32Array(this.maxTracks*12);this.trackColors=new Float32Array(this.maxTracks*12);const indices=new Uint32Array(this.maxTracks*6);for(let i=0;i<this.maxTracks;i++)indices.set([i*4,i*4+1,i*4+2,i*4+2,i*4+1,i*4+3],i*6);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(this.trackPositions,3).setUsage(THREE.DynamicDrawUsage));geo.setAttribute('color',new THREE.BufferAttribute(this.trackColors,3).setUsage(THREE.DynamicDrawUsage));geo.setIndex(new THREE.BufferAttribute(indices,1));geo.setDrawRange(0,0);this.tracks=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:.4,depthWrite:false,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2}));this.tracks.frustumCulled=false;this.tracks.renderOrder=2;scene.add(this.tracks);const zero=new THREE.Matrix4().makeScale(0,0,0);for(let i=0;i<this.maxClumps;i++)this.clumps.setMatrixAt(i,zero);
 }
 step(dt:number,v:RallyVehicle,enabled:boolean){const rand=this.rand;if(enabled&&v.speed>.8){for(let i=0;i<4;i++){const w=v.wheels[i];if(!w.contact){this.lastContacts[i]=null;continue;}this.emitCarry[i]+=dt*(8+v.speed*1.8+v.throttle*v.speed*2.1+w.slip*v.speed*2.5)*(w.mud?1.25:1);while(this.emitCarry[i]>=1){this.emitCarry[i]--;const p=this.particles[this.nextClump++%this.maxClumps],kick=1.1+v.throttle*4+w.slip*3;Object.assign(p,{x:w.contactPoint.x+(rand()-.5)*.3,y:w.contactPoint.y+.1,z:w.contactPoint.z+(rand()-.5)*.3,vx:v.velocity.x*.18-v.forward.x*kick+(rand()-.5)*3,vy:1.3+rand()*3.5+v.throttle*1.8,vz:v.velocity.z*.18-v.forward.z*kick+(rand()-.5)*3,life:.6+rand()*.7,max:1.2,size:.3+rand()*(w.mud?1.8:1.2)});if(!w.mud&&rand()<.35){const puff=this.puffs[this.nextPuff++%this.maxDust];Object.assign(puff,{x:p.x,y:p.y+.3,z:p.z,vx:p.vx*.6+.4,vy:.4+rand()*.6,vz:p.vz*.6,life:1.6+rand(),max:2.6,size:.2+rand()*.25});}}this.track(i,new THREE.Vector3(w.contactPoint.x,w.contactPoint.y+.029,w.contactPoint.z),w.mud,w.slip);}}else this.lastContacts=[null,null,null,null];
 for(let i=0;i<this.maxClumps;i++){const p=this.particles[i];if(p.life>0){p.life-=dt;p.vy-=9.81*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;if(p.life>.15){const n=nearestRoad(p.x,p.z),floor=n.distance<n.point.width/2?roadHeight(n.point,n.lateral):terrainHeight(p.x,p.z,n);if(p.y<floor){p.y=floor+.025;p.vy=Math.abs(p.vy)*.15;p.vx*=.65;p.vz*=.65;p.life=Math.min(p.life,.18);}}this.dummy.position.set(p.x,p.y,p.z);this.dummy.rotation.x+=dt*6;this.dummy.rotation.z+=dt*3;this.dummy.scale.setScalar(p.life>0?p.size*Math.min(1,p.life/.15):0);}else this.dummy.scale.setScalar(0);this.dummy.updateMatrix();this.clumps.setMatrixAt(i,this.dummy.matrix);}this.clumps.instanceMatrix.needsUpdate=true;
 for(let i=0;i<this.maxDust;i++){const p=this.puffs[i];if(p.life>0){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-dt*.7);p.vz*=Math.exp(-dt*.7);this.dustPositions.set([p.x,p.y,p.z],i*3);this.dustSizes[i]=p.size+(1-p.life/p.max)*.7;this.dustAlphas[i]=Math.min(.18,p.life*.14);}else this.dustAlphas[i]=0;}for(const key of ['position','pSize','pAlpha'])this.dust.geometry.attributes[key].needsUpdate=true;
 }
 private track(i:number,p:THREE.Vector3,mud:boolean,slip:number){const last=this.lastContacts[i];if(!last){this.lastContacts[i]=p;return;}const len=last.distanceTo(p);if(len<.27)return;if(len>3){this.lastContacts[i]=p;return;}const dx=(p.x-last.x)/len,dz=(p.z-last.z)/len,w=.15+slip*.05,k=(this.nextTrack++%this.maxTracks)*12;this.trackPositions.set([last.x-dz*w,last.y,last.z+dx*w,last.x+dz*w,last.y,last.z-dx*w,p.x-dz*w,p.y,p.z+dx*w,p.x+dz*w,p.y,p.z-dx*w],k);const c=mud?[.13,.095,.047]:[.26,.17,.085];for(let j=0;j<4;j++)this.trackColors.set(c,k+j*3);for(const key of ['position','color']){const a=this.tracks.geometry.attributes[key] as THREE.BufferAttribute;a.addUpdateRange(k,12);a.needsUpdate=true;}this.tracks.geometry.setDrawRange(0,Math.min(this.nextTrack,this.maxTracks)*6);this.lastContacts[i]=p;}
 resize(h:number,dpr:number){const m=this.dust.material as THREE.ShaderMaterial;m.uniforms.height.value=h;m.uniforms.pixelRatio.value=dpr;}
 clear(){this.particles.forEach(p=>p.life=0);this.puffs.forEach(p=>p.life=0);this.emitCarry=[0,0,0,0];this.nextTrack=0;this.lastContacts=[null,null,null,null];this.tracks.geometry.setDrawRange(0,0);}
 dispose(){for(const o of [this.clumps,this.dust,this.tracks]){o.geometry.dispose();(o.material as THREE.Material).dispose();o.removeFromParent();}}
}
export class RallyAudio{
 context:AudioContext|null=null;master:GainNode|null=null;engine:OscillatorNode|null=null;sub:OscillatorNode|null=null;engineGain:GainNode|null=null;noiseGain:GainNode|null=null;filter:BiquadFilterNode|null=null;enabled=true;
 samples:{source:AudioBufferSourceNode;gain:GainNode}[]=[];sampleLoading=false;kind='suv';
 private async loadSamples(){
  if(this.sampleLoading||!this.context)return;this.sampleLoading=true;const c=this.context;
  try{
   const buffers=await Promise.all(['engine','gravel','squeal'].map(async name=>{const response=await fetch('/assets/audio/'+name+'.mp3');if(!response.ok)throw Error('Audio unavailable');return c.decodeAudioData(await response.arrayBuffer());}));
   if(c.state==='closed')return;
   buffers.forEach((buffer,i)=>{const source=c.createBufferSource(),gain=c.createGain();source.buffer=buffer;source.loop=true;gain.gain.value=0;const filter=c.createBiquadFilter();filter.type=i===0?'lowpass':'highpass';filter.frequency.value=i===0?2100:220;source.connect(filter);filter.connect(gain);gain.connect(this.master!);source.start();this.samples.push({source,gain});});
  }catch{/* Keep the synthesis layer available when recorded audio cannot load. */}
 }
 cue(frequency=520){if(!this.context||!this.master||!this.enabled)return;const c=this.context,t=c.currentTime,osc=c.createOscillator(),gain=c.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(.001,t);gain.gain.linearRampToValueAtTime(.16,t+.012);gain.gain.exponentialRampToValueAtTime(.001,t+.18);osc.connect(gain);gain.connect(this.master);osc.start(t);osc.stop(t+.2);osc.onended=()=>{osc.disconnect();gain.disconnect();};}
 async start(){if(!this.context){const c=this.context=new AudioContext();this.master=c.createGain();this.master.gain.value=0;this.master.connect(c.destination);this.engine=c.createOscillator();this.engine.type='sawtooth';this.sub=c.createOscillator();this.filter=c.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=360;this.engineGain=c.createGain();this.engineGain.gain.value=.05;this.engine.connect(this.filter);this.sub.connect(this.filter);this.filter.connect(this.engineGain);this.engineGain.connect(this.master);this.engine.start();this.sub.start();const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const noise=c.createBufferSource();noise.buffer=buffer;noise.loop=true;const crunch=c.createBiquadFilter();crunch.type='bandpass';crunch.frequency.value=760;this.noiseGain=c.createGain();this.noiseGain.gain.value=0;noise.connect(crunch);crunch.connect(this.noiseGain);this.noiseGain.connect(this.master);noise.start();}if(this.context.state==='suspended')await this.context.resume();}
 update(rpm:number,throttle:number,speed:number,slip:number,active:boolean){if(!this.context)return;void this.loadSamples();const t=this.context.currentTime,recorded=this.samples.length===3;this.master?.gain.setTargetAtTime(this.enabled&&active?.45:0,t,.12);this.engine?.frequency.setTargetAtTime(Math.max(38,rpm/25),t,.07);this.sub?.frequency.setTargetAtTime(Math.max(25,rpm/50),t,.07);this.engineGain?.gain.setTargetAtTime((.045+throttle*.07)*(recorded?.13:1),t,.08);this.filter?.frequency.setTargetAtTime(250+throttle*550+rpm*.06,t,.1);this.noiseGain?.gain.setTargetAtTime(Math.min(recorded?.018:.09,speed*.0012+slip*.035),t,.1);if(recorded){this.samples[0].source.playbackRate.setTargetAtTime((this.kind==='truck'?.65:.78)+Math.max(0,rpm-900)/2700,t,.07);this.samples[0].gain.gain.setTargetAtTime(.24+throttle*.25,t,.08);this.samples[1].source.playbackRate.setTargetAtTime(.65+speed*.04,t,.12);this.samples[1].gain.gain.setTargetAtTime(Math.min(.16,speed*.005),t,.13);this.samples[2].gain.gain.setTargetAtTime(Math.max(0,slip-.45)*Math.min(1,speed*.08)*.15,t,.09);}}
 dispose(){void this.context?.close();}
}
