import type {HandlingMode} from './vehicle-config';
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {GATE_COUNT,WORLD_SIZE,COURSE_ID,COURSE_LENGTH,POND_CENTER,courseAt,nearestRoad,clamp,damp} from './course';
import {RallyVehicle,type DriveInput,type VehicleKind} from './vehicle';
import {createWorld,makeVisualVehicle,poseWheels,type WorldGraphics,type VisualVehicle,type Quality} from './world';
import {TireEffects,RallyAudio} from './effects';
import {RallyRendering} from './rendering';
import {EMPTY_SNAPSHOT,type GameSnapshot,type Phase} from './state';
import {RallyDrivingCamera} from './camera';
import {advanceVehicle} from './simulation';
import {DAYLIGHT} from './lighting';
const ZERO:DriveInput={steer:0,throttle:0,brake:0,handbrake:0};
export class RallyEngine{
 renderer:THREE.WebGLRenderer;pipeline!:RallyRendering;camera:THREE.PerspectiveCamera;physics:RAPIER.World;graphics!:WorldGraphics;vehicle!:RallyVehicle;visual!:VisualVehicle;effects!:TireEffects;audio=new RallyAudio();snapshot={...EMPTY_SNAPSHOT};phase:Phase='garage';resumePhase:Phase='driving';kind:VehicleKind='suv';quality:Quality=typeof matchMedia!=='undefined'&&matchMedia('(pointer:coarse)').matches?'balanced':'high';touch={...ZERO};keys=new Set<string>();sensitivity=1;cameraMode:'chase'|'hood'='chase';handlingMode:HandlingMode='rally';dynamicCamera=false;lowCameraAngle=false;bestTimes:Partial<Record<VehicleKind,number>>={};running=false;disposed=false;frameId=0;lastTime=0;lastRenderTime=0;accumulator=0;renderBudget=0;renderElapsed=0;hudTimer=0;countdown=3;lastCountdown=3;raceTime=0;splitTimes:number[]=[];bestSplits:Partial<Record<VehicleKind,number[]>>={};splitDelta:number|null=null;gate=1;penalties=0;peakSpeed=0;airtime=0;recoverTimer=0;messageUntil=0;message='';orbit=0;reflectionTimer=0;autoResolution=1;fps=60;fpsWindow=0;fpsFrames=0;cameraInitialized=false;interpolatedPosition=new THREE.Vector3();interpolatedQuaternion=new THREE.Quaternion();camPosition=new THREE.Vector3();camTarget=new THREE.Vector3();drivingCamera=new RallyDrivingCamera();
 constructor(public canvas:HTMLCanvasElement,public onSnapshot:(s:GameSnapshot)=>void){this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=DAYLIGHT.exposure;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.camera=new THREE.PerspectiveCamera(58,1,.12,1100);this.physics=new RAPIER.World({x:0,y:-9.81,z:0});this.physics.timestep=1/60;this.physics.integrationParameters.numSolverIterations=8;try{const p=JSON.parse(localStorage.getItem('wildtrail-prefs-v1')??'{}');if(['high','balanced','battery'].includes(p.quality))this.quality=p.quality;if(typeof p.sound==='boolean')this.audio.enabled=p.sound;if(p.vehicle==='truck')this.kind='truck';if(['baseline','refined','rally','rally-surface','rally-legacy'].includes(p.handlingMode))this.handlingMode=p.handlingMode;if(typeof p.dynamicCamera==='boolean')this.dynamicCamera=p.dynamicCamera;if(typeof p.lowCameraAngle==='boolean')this.lowCameraAngle=p.lowCameraAngle;this.bestTimes=JSON.parse(localStorage.getItem(this.recordKey('best'))??'{}');this.bestSplits=JSON.parse(localStorage.getItem(this.recordKey('splits'))??'{}');}catch{}}
 static async create(canvas:HTMLCanvasElement,onSnapshot:(s:GameSnapshot)=>void,progress:(n:number)=>void){await RAPIER.init();progress(.06);const e=new RallyEngine(canvas,onSnapshot);try{e.graphics=await createWorld(e.physics,progress);e.selectVehicle(e.kind);e.effects=new TireEffects(e.graphics.scene);e.pipeline=new RallyRendering(e.renderer,e.graphics.scene,e.camera);e.applyQuality();e.updateCamera(.016,true);await e.renderer.compileAsync(e.graphics.scene,e.camera);progress(1);e.snapshot.ready=true;e.emit();e.addListeners();e.running=true;e.lastTime=e.lastRenderTime=performance.now();e.frameId=requestAnimationFrame(e.frame);return e;}catch(error){e.dispose();throw error;}}
 selectVehicle(kind:VehicleKind){if(this.phase!=='garage'&&this.phase!=='finished')return;this.vehicle?.dispose();if(this.visual){this.visual.root.removeFromParent();this.visual.dispose();}this.kind=kind;this.audio.kind=kind;this.vehicle=new RallyVehicle(this.physics,kind,this.handlingMode);this.visual=makeVisualVehicle(kind,this.graphics.models.get(kind)!);this.graphics.scene.add(this.visual.root);this.effects?.clear();for(let i=0;i<50;i++){advanceVehicle(this.vehicle,this.physics,ZERO,1/60,false);}this.cameraInitialized=false;this.writePrefs();if(this.snapshot.ready)this.emit();}
 start(){if(!this.snapshot.ready)return;this.phase='countdown';this.countdown=3;this.lastCountdown=3;this.raceTime=0;this.splitTimes=[];this.splitDelta=null;this.gate=1;this.penalties=0;this.peakSpeed=0;this.airtime=0;this.recoverTimer=0;this.snapshot.isBest=false;this.vehicle.reset(courseAt(0));this.effects.clear();this.touch={...ZERO};this.keys.clear();this.message='';this.cameraInitialized=false;this.accumulator=0;this.updateGates();void this.audio.start().then(()=>this.audio.cue(480)).catch(()=>{this.audio.enabled=false;});this.emit();}
 pause(){if(this.phase==='driving'||this.phase==='countdown'){this.resumePhase=this.phase;this.phase='paused';this.touch={...ZERO};this.keys.clear();this.emit();}}
 resume(){if(this.phase==='paused'){this.phase=this.resumePhase;this.lastTime=performance.now();this.accumulator=0;this.emit();void this.audio.start().catch(()=>{});}}
 garage(){this.phase='garage';this.touch={...ZERO};this.keys.clear();this.effects.clear();this.vehicle.reset(courseAt(0));this.cameraInitialized=false;this.emit();}
 reset(){if(!['driving','countdown'].includes(this.phase))return;this.vehicle.reset(courseAt((this.gate-1)/GATE_COUNT));if(this.phase==='driving'){this.penalties++;this.raceTime+=3;this.notify('Back on the trail · +3s');}this.recoverTimer=0;this.effects.lastContacts=[null,null,null,null];this.cameraInitialized=false;this.emit();}
 private recordKey(type:'best'|'splits'){return `wildtrail-${type}-${COURSE_ID}${this.handlingMode==='baseline'?'':this.handlingMode==='refined'?'-refined-v1':this.handlingMode==='rally-legacy'?'-rally-v2':this.handlingMode==='rally-surface'?'-rally-v3':'-rally-v4'}`;}
 setHandlingMode(mode:HandlingMode){
  if(!['baseline','refined','rally','rally-surface','rally-legacy'].includes(mode)||mode===this.handlingMode||!['garage','paused','finished'].includes(this.phase))return;
  this.handlingMode=mode;this.vehicle.setHandlingMode(mode);this.bestTimes={};this.bestSplits={};
  try{this.bestTimes=JSON.parse(localStorage.getItem(this.recordKey('best'))??'{}');this.bestSplits=JSON.parse(localStorage.getItem(this.recordKey('splits'))??'{}');}catch{}
  this.writePrefs();this.splitDelta=null;
  if(this.phase==='paused')this.start();else if(this.phase==='finished')this.garage();
  this.emit();
 }
 setTouch(input:Partial<DriveInput>){Object.assign(this.touch,input);}setSound(value:boolean){this.audio.enabled=value;this.writePrefs();if(value)void this.audio.start().catch(()=>{});this.emit();}setQuality(value:Quality){this.quality=value;this.autoResolution=1;this.applyQuality();this.writePrefs();this.emit();}setSensitivity(value:number){this.sensitivity=clamp(value,.65,1.4);}setDynamicCamera(value:boolean){this.dynamicCamera=value;this.writePrefs();this.emit();}setLowCameraAngle(value:boolean){this.lowCameraAngle=value;this.writePrefs();this.emit();}changeCamera(){this.cameraMode=this.cameraMode==='chase'?'hood':'chase';this.cameraInitialized=false;this.emit();}
 notify(message:string,seconds=2.5){this.message=message;this.messageUntil=this.renderElapsed+seconds;}private writePrefs(){try{localStorage.setItem('wildtrail-prefs-v1',JSON.stringify({quality:this.quality,sound:this.audio.enabled,vehicle:this.kind,handlingMode:this.handlingMode,dynamicCamera:this.dynamicCamera,lowCameraAngle:this.lowCameraAngle}));}catch{}}
 private input():DriveInput{const k=this.keys,left=k.has('a')||k.has('arrowleft'),right=k.has('d')||k.has('arrowright');let steer=this.touch.steer,throttle=Math.max(this.touch.throttle,k.has('w')||k.has('arrowup')?1:0),brake=Math.max(this.touch.brake,k.has('s')||k.has('arrowdown')?1:0),handbrake=Math.max(this.touch.handbrake,k.has(' ')?1:0);if(left||right)steer=(left?1:0)-(right?1:0);for(const p of navigator.getGamepads?.()??[]){if(!p?.connected)continue;const axis=p.axes[0]??0;if(Math.abs(axis)>.06)steer=-clamp((Math.abs(axis)-.06)/.94,0,1)*Math.sign(axis);throttle=Math.max(throttle,p.buttons[7]?.value??0);brake=Math.max(brake,p.buttons[6]?.value??0);handbrake=Math.max(handbrake,p.buttons[0]?.value??0);break;}return {steer:clamp(steer*this.sensitivity,-1,1),throttle,brake,handbrake};}
 private step(dt:number){const active=this.phase==='driving';if(active||this.phase==='countdown'||this.phase==='garage'){advanceVehicle(this.vehicle,this.physics,this.input(),dt,active);this.effects.step(dt,this.vehicle,active);}if(this.phase==='countdown'){this.countdown-=dt;const count=Math.ceil(this.countdown);if(count!==this.lastCountdown){this.lastCountdown=count;this.audio.cue(count===0?960:480);}if(this.countdown<=0){this.phase='driving';this.notify('GO',.9);}}if(this.phase==='driving'){this.raceTime+=dt;this.peakSpeed=Math.max(this.peakSpeed,this.vehicle.speed*3.6);if(this.vehicle.airborne>.05)this.airtime+=dt;const p=this.vehicle.position,n=nearestRoad(p.x,p.z),target=courseAt(this.gate/GATE_COUNT),vel=this.vehicle.velocity,q=this.vehicle.rotation;if(Math.hypot(target.x-p.x,target.z-p.z)<Math.max(8.6,target.width*.65)&&vel.x*target.tx+vel.z*target.tz>0){if(this.gate===GATE_COUNT&&this.raceTime>25)this.finish();else if(this.gate<GATE_COUNT){this.splitTimes.push(this.raceTime);const benchmark=this.bestSplits[this.kind]?.[this.gate-1];this.splitDelta=typeof benchmark==='number'?this.raceTime-benchmark:null;this.gate++;this.notify('CHECKPOINT '+(this.gate-1)+' / '+(GATE_COUNT-1),1.1);this.updateGates();}}const up=1-2*(q.x*q.x+q.z*q.z),water=Math.hypot(p.x-POND_CENTER.x,p.z-POND_CENTER.z)<24&&p.y<-.9;this.recoverTimer=up<.2?this.recoverTimer+dt:0;if(this.recoverTimer>3||p.y<-24||Math.abs(p.x)>WORLD_SIZE*.47||Math.abs(p.z)>WORLD_SIZE*.47||water)this.reset();if(this.renderElapsed>this.messageUntil&&this.vehicle.speed>3&&vel.x*n.point.tx+vel.z*n.point.tz<-1.8)this.notify('Wrong way',.5);else if(this.renderElapsed>this.messageUntil&&n.distance>n.point.width/2+4)this.notify('Off trail · recover to continue',.5);}}
 private finish(){this.phase='finished';this.touch={...ZERO};this.keys.clear();const old=this.bestTimes[this.kind];this.snapshot.isBest=!old||this.raceTime<old;if(this.snapshot.isBest){this.bestTimes[this.kind]=this.raceTime;this.bestSplits[this.kind]=[...this.splitTimes,this.raceTime];try{localStorage.setItem(this.recordKey('best'),JSON.stringify(this.bestTimes));localStorage.setItem(this.recordKey('splits'),JSON.stringify(this.bestSplits));}catch{}}this.emit();}
 private updateGates(){this.graphics.gates.forEach((g,i)=>{if(i===0)return;g.traverse(o=>{if(o instanceof THREE.Mesh&&o.geometry instanceof THREE.PlaneGeometry)(o.material as THREE.MeshStandardMaterial).color.set(i===this.gate?'#d5f75b':i<this.gate?'#86917b':'#efeee0');});});}
 private updateCamera(dt:number,force=false){
 const v=this.vehicle,a=this.phase==='paused'||this.phase==='finished'?1:clamp(this.accumulator/(1/60),0,1);
 const prev=new THREE.Vector3(v.previousPosition.x,v.previousPosition.y,v.previousPosition.z),now=new THREE.Vector3(v.position.x,v.position.y,v.position.z);
 this.interpolatedPosition.copy(prev).lerp(now,a);
 this.interpolatedQuaternion.set(v.previousRotation.x,v.previousRotation.y,v.previousRotation.z,v.previousRotation.w).slerp(new THREE.Quaternion(v.rotation.x,v.rotation.y,v.rotation.z,v.rotation.w),a);
 this.visual.root.position.copy(this.interpolatedPosition);this.visual.root.quaternion.copy(this.interpolatedQuaternion);poseWheels(this.visual,v.wheels,v.brake);
 const w=Math.max(1,this.canvas.clientWidth),h=Math.max(1,this.canvas.clientHeight),portrait=w<h;
 let fov:number;
 if(this.phase==='garage'){
  const forward=new THREE.Vector3(0,0,-1).applyQuaternion(this.interpolatedQuaternion);forward.y=0;forward.normalize();
  const right=new THREE.Vector3().crossVectors(forward,new THREE.Vector3(0,1,0));
  this.orbit+=dt*.025;const angle=.77+Math.sin(this.orbit)*.10;
  const eye=this.interpolatedPosition.clone().addScaledVector(forward,Math.cos(angle)*7.7).addScaledVector(right,Math.sin(angle)*8.9);eye.y+=2.15;
  if(portrait)eye.sub(this.interpolatedPosition).multiplyScalar(1.26).add(this.interpolatedPosition);
  const target=this.interpolatedPosition.clone();target.y+=.25;
  if(portrait)this.camera.setViewOffset(w,h,0,h*.19,w,h);else this.camera.setViewOffset(w,h,-w*.17,0,w,h);
  if(force||!this.cameraInitialized){this.camPosition.copy(eye);this.camTarget.copy(target);}
  else{this.camPosition.lerp(eye,1-Math.exp(-8*dt));this.camTarget.lerp(target,1-Math.exp(-8*dt));}
  fov=portrait?50:43;
 }else{
  this.camera.clearViewOffset();
  const pose=this.drivingCamera.update({position:this.interpolatedPosition,rotation:this.interpolatedQuaternion,velocity:v.velocity,speed:v.speed,forwardSpeed:v.forwardSpeed,steer:v.steer,kind:this.kind,mode:this.cameraMode,dynamic:this.dynamicCamera,lowAngle:this.lowCameraAngle,portrait,dt,force:force||!this.cameraInitialized},this.physics);
  this.camPosition.copy(pose.position);this.camTarget.copy(pose.target);fov=pose.fov;
 }
 this.cameraInitialized=true;this.camera.position.copy(this.camPosition);this.camera.up.set(0,1,0);this.camera.lookAt(this.camTarget);
 this.camera.fov=damp(this.camera.fov,fov,4,dt);this.camera.updateProjectionMatrix();
 this.graphics.sun.target.position.copy(this.interpolatedPosition);this.graphics.sun.position.copy(this.interpolatedPosition).add(DAYLIGHT.sunOffset);this.graphics.sun.target.updateMatrixWorld();
 }
 private frame=(time:number)=>{if(!this.running||this.disposed)return;const dt=clamp((time-this.lastTime)/1000,0,.0667);this.lastTime=time;this.renderElapsed+=dt;this.accumulator+=dt;this.renderBudget+=dt;this.fpsWindow+=dt;if(this.fpsWindow>=1){this.fps=this.fpsFrames/this.fpsWindow;this.fpsFrames=0;this.fpsWindow=0;if(this.quality==='balanced'&&this.fps<34&&this.autoResolution>.65){this.autoResolution=Math.max(.65,this.autoResolution-.06);this.resize();}}let steps=0;while(this.accumulator>=1/60&&steps++<4){this.step(1/60);this.accumulator-=1/60;}const period=1/(this.quality==='battery'?30:60);if(this.renderBudget<period-.0005){this.frameId=requestAnimationFrame(this.frame);return;}const renderDt=clamp((time-this.lastRenderTime)/1000,0,.1);this.lastRenderTime=time;this.renderBudget=Math.max(0,this.renderBudget-period);this.updateCamera(renderDt);this.graphics.scenery.update(this.interpolatedPosition,this.renderElapsed,this.quality);this.graphics.mirror.visible=this.quality!=='battery'&&Math.hypot(this.vehicle.position.x-POND_CENTER.x,this.vehicle.position.z-POND_CENTER.z)<75;this.pipeline.render(renderDt);this.fpsFrames++;this.audio.update(this.vehicle.rpm,this.vehicle.throttle,this.vehicle.speed,Math.max(...this.vehicle.wheels.map(w=>w.slip)),this.phase==='driving'||this.phase==='countdown');this.hudTimer+=renderDt;if(this.hudTimer>.07){this.hudTimer=0;this.emit();}this.frameId=requestAnimationFrame(this.frame);};
 private emit(){const v=this.vehicle,q=v?.rotation??{x:0,y:0,z:0,w:1};const road=nearestRoad(v?.position.x??0,v?.position.z??0).point,a=courseAt(road.s+12/COURSE_LENGTH),b=courseAt(road.s+48/COURSE_LENGTH),angle=Math.atan2(a.tx*b.tz-a.tz*b.tx,a.tx*b.tx+a.tz*b.tz),turn=Math.abs(angle)<.16?'straight':angle>0?'right':'left',intensity=Math.abs(angle)>1.05?'HAIRPIN':Math.abs(angle)>.55?'HARD':'EASY';this.snapshot={...this.snapshot,phase:this.phase,vehicle:this.kind,paceTurn:turn,paceNote:turn==='straight'?'STRAIGHT':intensity+' '+turn.toUpperCase(),splitDelta:this.splitDelta,speed:v?.speed*3.6||0,gear:v?.gear??1,rpm:v?.rpm??900,steer:v?.steer??0,time:this.raceTime,best:this.bestTimes[this.kind]??null,gate:this.gate,progress:this.phase==='finished'?1:Math.min(.99,nearestRoad(v?.position.x??0,v?.position.z??-146).point.s),surface:v?.surface??'LOOSE DIRT',countdown:Math.ceil(this.countdown),message:this.renderElapsed<this.messageUntil?this.message:'',camera:this.cameraMode,handlingMode:this.handlingMode,dynamicCamera:this.dynamicCamera,lowCameraAngle:this.lowCameraAngle,sound:this.audio.enabled,quality:this.quality,fps:Math.round(this.fps),position:{x:v?.position.x??0,z:v?.position.z??-146,yaw:Math.atan2(2*(q.w*q.y+q.x*q.z),1-2*(q.y*q.y+q.z*q.z))},penalties:this.penalties,peakSpeed:this.peakSpeed,airtime:this.airtime};this.onSnapshot(this.snapshot);}
 private resize=()=>{const w=Math.max(1,this.canvas.clientWidth),h=Math.max(1,this.canvas.clientHeight),coarse=matchMedia('(pointer:coarse)').matches,dpr=Math.min(window.devicePixelRatio||1,this.quality==='high'?(coarse?1.6:1.7):this.quality==='battery'?1:coarse?1.2:1.4)*this.autoResolution;this.renderer.setPixelRatio(dpr);this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.effects?.resize(h,dpr);this.pipeline?.resize(w,h,dpr,this.quality);this.cameraInitialized=false;};
 private applyQuality(){const high=this.quality==='high';this.graphics.sun.shadow.mapSize.set(high?3072:this.quality==='battery'?1024:2048,high?3072:this.quality==='battery'?1024:2048);this.graphics.sun.shadow.map?.dispose();this.graphics.sun.shadow.map=null;this.effects.clumps.castShadow=high;this.resize();}
 private keyDown=(e:KeyboardEvent)=>{const key=e.key.toLowerCase(),target=e.target as HTMLElement;if(target?.closest('input,textarea,[role="dialog"],[role="switch"],[role="slider"],[role="combobox"],[role="radio"]')||(target?.closest('button')&&[' ','enter'].includes(key)))return;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key)&&this.phase!=='paused')e.preventDefault();if(!e.repeat){if(key==='escape'){if(this.phase==='paused')this.resume();else this.pause();}if(key==='r')this.reset();if(key==='c')this.changeCamera();if((key==='enter'||key===' ')&&this.phase==='garage')this.start();}this.keys.add(key);};private keyUp=(e:KeyboardEvent)=>this.keys.delete(e.key.toLowerCase());private blur=()=>{this.keys.clear();this.touch={...ZERO};this.pause();};private visibility=()=>{if(document.hidden)this.blur();};private contextLost=(e:Event)=>{e.preventDefault();this.pause();this.notify('Graphics paused · reload to continue',60);this.emit();};
 private addListeners(){window.addEventListener('keydown',this.keyDown);window.addEventListener('keyup',this.keyUp);window.addEventListener('resize',this.resize);window.addEventListener('blur',this.blur);document.addEventListener('visibilitychange',this.visibility);this.canvas.addEventListener('webglcontextlost',this.contextLost);}
 dispose(){this.running=false;this.disposed=true;cancelAnimationFrame(this.frameId);window.removeEventListener('keydown',this.keyDown);window.removeEventListener('keyup',this.keyUp);window.removeEventListener('resize',this.resize);window.removeEventListener('blur',this.blur);document.removeEventListener('visibilitychange',this.visibility);this.canvas.removeEventListener('webglcontextlost',this.contextLost);this.audio.dispose();this.effects?.dispose();this.visual?.dispose();this.pipeline?.dispose();this.graphics?.dispose();this.physics.free();this.renderer.dispose();}
}
